### ISSUE TITLE
sendAndVerifyAttestation method returns an error

### ISSUE THREAD

**Issue by Miti063** [rajivshah3/react-native-google-safetynet#369] opened 2020-05-27 10:20 UTC
Using the basic example from the repo, sendAndVerifyAttestation method returns an error. 

Version Detail:

`
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-google-safetynet": "^1.0.0"
`

Here is my code: 

```
SafetyNet.isPlayServicesAvailable()
      .then(result => {
        if (result === true) {
          return SafetyNet.generateNonce(24)
        }
        throw new Error('play services not available.');
      })
      .then(nonce => {
        SafetyNet.sendAttestationRequest(nonce, 'APIKEY').then(isRooted => {
          console.log(isRooted)
        }).catch(err => console.log('err',err));
      }).catch(error => console.log(error));

```
Error logs: 
```
{
   "framesToPop":1,
   "nativeStackAndroid":[
      {
         "methodName":"fromStatus",
         "lineNumber":4,
         "file":null
      },
      {
         "methodName":"zaf",
         "lineNumber":2,
         "file":null
      },
      {
         "methodName":"onComplete",
         "lineNumber":6,
         "file":null
      },
      {
         "methodName":"zaa",
         "lineNumber":172,
         "file":null
      },
      {
         "methodName":"setResult",
         "lineNumber":131,
         "file":null
      },
      {
         "methodName":"zza",
         "lineNumber":7,
         "file":null
      },
      {
         "methodName":"dispatchTransaction",
         "lineNumber":155,
         "file":null
      },
      {
         "methodName":"onTransact",
         "lineNumber":22,
         "file":null
      },
      {
         "methodName":"execTransactInternal",
         "lineNumber":1028,
         "file":"Binder.java"
      },
      {
         "methodName":"execTransact",
         "lineNumber":1001,
         "file":"Binder.java"
      }
   ],
   "userInfo":null,
   "code":"EUNSPECIFIED"
}
```

**Comment by rajivshah3** [comment] 2020-05-27 19:00
I haven’t tested this on RN 0.60+ so maybe it’s not linking properly as mentioned in #322

**Comment by rajivshah3** [comment] 2020-05-27 19:39
Duplicate of #135

**Closed by rajivshah3** 2020-05-27 19:39 UTC

**Comment by gkasireddy202** [comment] 2022-04-20 08:46
Hi,

I got error **err [Error: 7: ]** to below code.

   SafetyNet.isPlayServicesAvailable()
      .then(result => {
        if (result === true) {
          return SafetyNet.generateNonce(24)
        }
        throw new Error('play services not available.');
      })
      .then(nonce => {
        SafetyNet.sendAttestationRequest(nonce, API_KEY).then(isRooted => {
          console.log(isRooted)
        }).catch(err => console.log('err',err));
      }).catch(error => console.log(error))
